Fixes issue #2 macOS setup
ClojureBridgeBA/curriculum pull request #20
Opened 2017-02-26 23:11 UTC by marcote

Hi there,

This is the initial PR handling #2 . I've created a new file `setup_macos_es.md`since macOS is the new name of the Mac operating system.
Please review the translation, I tried to make it as close to the original as posible but adding more "spanish-like" expressions where I saw a fit. 

Please, review and sorry about the delay, I've been busier than expected.

2017-02-28 01:41 UTC, allentiak commented
Hola, @marcote,
Muchas gracias por tu trabajo. Mañana veo la traducción. Por ahora, un comentario rápido. ¿Verificaste que los enlaces a las imágenes anden? (Yo tuve que modificar todos los enlaces. Mirá los cambios que tuve que hacer en los enlaces en #9.)

2017-02-28 17:34 UTC, allentiak requested changes
Muchas gracias por tu trabajo. ¿Podrías revisar lo que te marco abajo, por favor?

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +* Verifica tu setup
"Verifica" --> ¿"Verificar"?

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +El prompt (dónde tipearas tus comandos) puede que luzca diferente: usualmente muestra el nombre de tu computadora y el nombre de usuario, ademas de la carpeta o directorio donde te encuentres actualm
"Prompt" --> ¿"Símbolo de sistema"? (Si bien no me gusta nada, es lo que se usa en forma "estándar"...)
Hay varias ocurrencias de esto.

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Para el resto de este setup, te diré que comandos ejecutar en tu terminal. Cuando diga eso, me refiero a "tipea el comando en la terminal y luego presiona la tecla Enter".
"Para el resto de este setup" --> ¿"Para el resto de este proceso"?
(¿Quizás "configuración" sería una buena traducción para el resto de los casos?)

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Para verificar si ya tienes git instalado tipea  `git --version`. Si posees la versión `git version 1.9.3 (Apple Git-50)` o una version superior estaras bien.
estaras --> estarás

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Si no, visita [git-scm](http://git-scm.com). Haz click en "Downloads para Mac".
"Downloads" --> ¿"Descargas"?

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +El instalador de git debería bajar automaticamente. Si no lo hace, haz click en el link para realizar una descarga manual.
"una descarga manual." --> ¿"una descarga en forma manual."? / ¿"la descarga manualmente."?

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Si ya haz utilizado Git anteriormente entonces deberías poseer user.name y user.email configurado.
"Si ya haz utilizado Git anteriormente entonces deberías poseer user.name y user.email configurado."
--> ¿"Si ya haz utilizado Git, entonces deberías tener `user.name` y `user.email` configurados."?

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Si no haz utilizado anteriormente, tipea lo siguiente en la terminal:
"utilizado anteriormente" --> "utilizado Git anteriormente"

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +> Si tienes problema el articulo <http://osxdaily.com/2015/10/17/how-to-install-java-in-os-x-el-capitan/>, puede ayudarte.
"problema el" --> "problemas, el"

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Leiningen es una herramienta usada desde la línea de comando para manejar proyectos de Clojure.
"línea de comando" --> "línea de comandos"
"proyectos de Clojure." --> "proyectos en Clojure."

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Para instalar `lein` ejecuta los siguientes comandos en tu terminal; se te pedirá que ingreses tu contraseña para al menos el primer comando que comienza con `sudo` (El caracter `%` es un simbolo típ
"prompt": ver comentario sobre L22

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Si no lo puedes ver `/usr/local/bin/lein` como parece arriba, haz lo siguiente:
"no lo puedes ver" --> "no puedes ver"

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Luego que hayas configurado como descripto anteriormente, ejecuta el comando `lein version`. Esto puede tomar unos momentos ya que descargará algunos recursos requirados la primera vez. Si este paso
"momentos" --> "momentos,"

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +> El archivo jar es sencillo para comenzar.
Faltan los puntos finales en las dos primeras oraciones.

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Una vez que la descarga del archivo finalice, queremos iniciar el editor.
"queremos" --> "querremos" (presente con idea de futuro)

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Haz instalado y configurado Java, Leiningen, Nightcode y Git en tu computadora -- todas las herramientas que necesitaras para este workshop. Antes de comenzar, cercirnarnos de que esten bien configur
"workshop" --> "taller"

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Cuando Leinigen inicia, deberías ver el prompt `user =>` en tu terminal.
"prompt" idem anterior

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Ahora estas lista para usar el __REPL__, el cual vas a aprender de el pronto.
"Ahora estas lista para usar el __REPL__, el cual vas a aprender de el pronto."
-->
"Ahora estás lista para usar el __REPL__, del cual vas a aprender pronto."

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Esto clonará el repositorio `welcometoclojurebridge` el cual incluye aplicaciones Clojure de ejemplo.
"`welcometoclojurebridge` el" --> "`welcometoclojurebridge`, el "

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Al la derecha del final de la pantalla, typea `(+ 1 1)` en la ventana. Debería verse similar a la siguiente imagen:
"typea" --> "tipea"

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +A small triangle on the center is the *turtle*.
Este texto en inglés está de más.

2017-02-28 17:34 UTC, allentiak commented on outline/setup_macos_es.md
> +Felicitaciones! Haz abierto y ejecutado tu primer aplicación Clojure, y tu instalación y setup han sido completado!
"setup" --> ¿"configuración"?

2017-03-01 02:14 UTC, nberger commented
Hey @marcote, thanks for the PR!

Even though some fixes are needed here as pointed out by @allentiak (also, the file should be moved to `es/outline/setup_macos.md`), I know you are pretty busy these days so I think we should just merge the PR as is. Then somebody (even you) could propose additional changes from there. We could even create an issue titled "Improve spanish translation of setup_macos_es.md"

What do you think @allentiak & @marcote?

2017-03-02 14:57 UTC, merged